// import '@mantine/core/styles.css';
// import { MantineProvider } from '@mantine/core';
// import { ColorSchemeScript } from '@mantine/core';
import './global.css';

export const metadata = {
  title: 'Welcome to blog-frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* <MantineProvider> */}
          {/* <ColorSchemeScript /> */}
          {children}
          {/* </MantineProvider> */}
      </body>
    </html>
  );
}
